workflows:
  ios-capacitor:
    name: iOS Capacitor (TestFlight)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - appstore_connect
      node: 22
      vars:
        BUNDLE_IDENTIFIER: com.wildmoustachegames.flagiq
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.wildmoustachegames.flagiq
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web app
        script: |
          if [[ -z "${REACT_APP_SUPABASE_URL:-}" || -z "${REACT_APP_SUPABASE_ANON_KEY:-}" ]]; then
            echo "Missing required env vars for build: REACT_APP_SUPABASE_URL and/or REACT_APP_SUPABASE_ANON_KEY"
            exit 1
          fi
          npx cross-env ESLINT_NO_DEV_ERRORS=true npm run build
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Initialize keychain
        script: keychain initialize
      - name: Configure code signing
        script: |
          app_store_connect fetch-signing-files "$BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Set iOS build versions
        script: |
          MARKETING_VERSION="${MARKETING_VERSION:-1.0}"
          CURRENT_PROJECT_VERSION="${CM_BUILD_NUMBER:-8}"
          echo "MARKETING_VERSION=$MARKETING_VERSION" >> "$CM_ENV"
          echo "CURRENT_PROJECT_VERSION=$CURRENT_PROJECT_VERSION" >> "$CM_ENV"
          BUILD_SETTINGS=$(xcodebuild -showBuildSettings -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -target "$XCODE_SCHEME")
          INFO_PLIST_RELATIVE=$(echo "$BUILD_SETTINGS" | awk -F ' = ' '/INFOPLIST_FILE/ {print $2; exit}')
          WORKSPACE_DIR=$(dirname "$XCODE_WORKSPACE")
          if [[ "$INFO_PLIST_RELATIVE" = /* ]]; then
            INFO_PLIST="$INFO_PLIST_RELATIVE"
          else
            INFO_PLIST="$WORKSPACE_DIR/$INFO_PLIST_RELATIVE"
          fi
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $MARKETING_VERSION" "$INFO_PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $MARKETING_VERSION" "$INFO_PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CURRENT_PROJECT_VERSION" "$INFO_PLIST" || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $CURRENT_PROJECT_VERSION" "$INFO_PLIST"
          echo "Resolved Info.plist: $INFO_PLIST"
          echo "Bundle identifier: $(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$INFO_PLIST")"
          echo "CFBundleShortVersionString: $(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$INFO_PLIST")"
          echo "CFBundleVersion: $(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$INFO_PLIST")"
          echo "Final CFBundleVersion (App target): $(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$INFO_PLIST")"
      - name: Set iOS build number
        script: |
          #!/usr/bin/env bash
          set -e

          BUILD_NUMBER="${CM_BUILD_NUMBER:-8}"
          echo "BUILD_NUMBER=$BUILD_NUMBER"

          INFO_PLIST="ios/App/App/App/Info.plist"

          # Set build number (CFBundleVersion)
           /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$INFO_PLIST" \
           || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUMBER" "$INFO_PLIST"

          # Print to confirm
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$INFO_PLIST" || true
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$INFO_PLIST" || true
      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
