workflows:
  ios-capacitor:
    name: iOS Capacitor (TestFlight)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - appstore_connect
      node: 22
      vars:
        BUNDLE_IDENTIFIER: com.wildmoustachegames.flagiq
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.wildmoustachegames.flagiq
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web app
        script: npx cross-env ESLINT_NO_DEV_ERRORS=true npm run build
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Initialize keychain
        script: keychain initialize
      - name: Configure code signing
        script: |
          app_store_connect fetch-signing-files "$BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Set iOS build number
        script: |
          INFO_PLIST="ios/App/App/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CM_BUILD_NUMBER" "$INFO_PLIST"
          echo "Bundle identifier: $(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$INFO_PLIST")"
          echo "CFBundleShortVersionString: $(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$INFO_PLIST")"
          echo "CFBundleVersion: $(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$INFO_PLIST")"
      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
